### ISSUE TITLE
리스트 화면 비움, 삭제 처리

### ISSUE THREAD

**Issue by oddukgi** [Swift-Coding-Club/throw_away#24]
## Task 
- [x] 리스트 화면 비움 처리 
- [x] 한개 삭제 처리
- [x] 다중 삭제 처리
